disabled_rules: # you can disable rules you don't like
  - force_cast
  - force_unwrapping
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_end_indentation
  - extension_access_modifier

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - JSON
